### ISSUE TITLE
Bonelib 2.0.1 keep crashing

### ISSUE THREAD

**Issue by Koin05** [yowchap/BoneLib#26]
Include the following info or it won't be looked into.
Store (Steam, Oculus): Steam
Headset (Index, Quest 2, etc): Quest 2
A detailed description of the issue: I use MelonLoader, but when it says "Initializing bonelib.2.0.1..." it crashes.
Steps to recreate the issue: Install MelonLoader, install BoneLib in "Mods" folder and start the game.

Also upload your log file from **BONELAB\MelonLoader\Latest.log** even if there are no errors in it.
[Latest.log](https://github.com/yowchap/BoneLib/files/10251622/Latest.log)

**Comment by Adi453** [comment]
Purchase the game

**Comment by adamd3v** [comment]
You should buy the game

**Comment by EthanNinja11426** [comment]
how was this fixed bc its happening to me
