### ISSUE TITLE
BoneMenu option in settings is missing

### ISSUE THREAD

**Issue by Maxb0tbeep** [yowchap/BoneLib#28]
Include the following info or it won't be looked into.
Store: steam
Headset: Q2
A detailed description of the issue: In the preferences menu there isn't an option for the bonemenu? Do I have to enable it?
Steps to recreate the issue: 
Open bonelab, open menu by pressing Y button, open preferences, not there

[Latest.log](https://github.com/yowchap/BoneLib/files/10265502/Latest.log)

**Comment by Adi453** [comment]
Your version of Bonelib is outdated, the BoneMenu was added in v2.0.0
