### ISSUE TITLE
Bonelab crashing when using BoneLib

### ISSUE THREAD

**Issue by Nicoszoki** [yowchap/BoneLib#31]
Include the following info or it won't be looked into.
Store (Steam, Oculus): Steam
Headset (Index, Quest 2, etc): Quest 2
A detailed description of the issue: I started bonelab after installing MelonLoader and it worked, then I installed BoneLib and the game crashes
Steps to recreate the issue: Install MelonLoader - Install BoneLib - play

Also upload your log file from **BONELAB\MelonLoader\Latest.log** even if there are no errors in it.
[MelonLoader_23-01-12_19-30-16.718.log](https://github.com/yowchap/BoneLib/files/10406727/MelonLoader_23-01-12_19-30-16.718.log)

**Comment by yowchap** [comment]
Buy the game.

**Comment by PedroViniVince** [comment]
nice pirated copy detection.
too bad people already know how to by pass it.
