### ISSUE TITLE
Bonemenu missing in beta

### ISSUE THREAD

**Issue by FoxivanFable** [yowchap/BoneLib#36]
im not a mod creator and i dont even know how the bone menu was added into the game in the first place, but im gonna say this anyway. 
when using the public beta for patch 3, the bonemenu just, isnt there. everything else the mod has is but the bonemenu just is not shown, again i dont know how this all works, but updating it to work with this beta could be a quick and easy fix (if its not, no hard feelings)

**Comment by DylanZutner** [comment]
get the latest patch

**Comment by FoxivanFable** [comment]
> get the latest patch

yep, i’ve already been using it for a bit. this report is outdated now
