### ISSUE TITLE
Bonemenu isn't appearing.

### ISSUE THREAD

**Issue by bilbusser** [yowchap/BoneLib#38]
Include the following info or it won't be looked into.
Store (Steam, Oculus): Oculus
Headset (Index, Quest 2, etc): Quest 2
A detailed description of the issue: I put the files where they were supposed to go but Bonemenu doesn't show up in settings.
Steps to recreate the issue: I can't

Also upload your log file from **BONELAB\MelonLoader\Latest.log** even if there are no errors in it.
[MelonLoader_23-03-06_22-50-53.114.log](https://github.com/yowchap/BoneLib/files/10905254/MelonLoader_23-03-06_22-50-53.114.log)

**Comment by LilSynths** [comment]
I play Quest 2 PCVR on Steam and the same has happened to me and a friend, Bonemenu just isn't appearing so I imagine this is just a new update issue rn

**Comment by DylanZutner** [comment]
If your not on the beta patch then get the version 2.2.0

**Comment by LilSynths** [comment]
Ahh lovely, cheers mate

**Comment by DylanZutner** [comment]
you should probably close it

**Comment by Sneakyboi07** [comment]
I bought the game on oculus and play on oculus 2 but its connected to my pc.
The bonemenu showed up but recently has just stopped.
It was also suddenly and not after i had installed a mod or something like that

[MelonLoader_23-03-04_12-24-03.677.log](https://github.com/yowchap/BoneLib/files/10948766/MelonLoader_23-03-04_12-24-03.677.log)

**Comment by DylanZutner** [comment]
It probably auto updated go back to the version 2.2.0 and delete the auto updater in plugins

**Comment by LilSynths** [comment]
Life-saver Dylan, got it working now, cheers mate

**Comment by listokerup** [comment]
> If your not on the beta patch then get the version 2.2.0 instead of the latest one

still not work
