### ISSUE TITLE
Bonelib missing dependencies

### ISSUE THREAD

**Issue by EthanNinja11426** [yowchap/BoneLib#42]
Include the following info or it won't be looked into.

Store (Steam, Oculus): Oculus

Headset (Index, Quest 2, etc): Quest 2

A detailed description of the issue: Only mod installed is bonelib, it says it is missing 4 dependencies and that is the only problem in the log so i will put a image, also the game just crashes during the loading screen and it crashes when it says "initializing mod: bonelib.dll"

Steps to recreate the issue: Try running bone;ab with bonelib.dll and hope it breaks idk

Log:
![WhatsApp Image 2023-03-17 at 19 21 56](https://user-images.githubusercontent.com/79656891/226002691-1b5162e8-449d-443f-be7c-eeb2039cdd46.jpg)

**Comment by Adi453** [comment]
Downgrade to ML 0.5.7

**Comment by EthanNinja11426** [comment]
> Downgrade to ML 0.5.7

can you send me link to it

**Comment by EthanNinja11426** [comment]
> Downgrade to ML 0.5.7

you dont gotta do it but HOLY FUCK IT WORKED TYSM IVE BEEN DOING THIS FOR A WEEK NOW
