### ISSUE TITLE
BoneLib 3.0 Crashing Bonelab upon launch

### ISSUE THREAD

**Issue by NM69421** [yowchap/BoneLib#78]
Include the following info or it won't be looked into.
Store (Steam, Oculus): Oculus (PC)
Headset (Index, Quest 2, etc): Quest 3
A detailed description of the issue:  Bonelib is causing a error upon start of bonelab. I have Just Reinstalled the game after a clean wipe and manually installed everything. 
Steps to recreate the issue: I'm not quite Sure. Game Version is 1.985.34555 (Public Beta) with Melon Loader 0.5.7 and Bonelib 3.0. No other mods are installed

Also upload your log file from **BONELAB\MelonLoader\Latest.log** even if there are no errors in it.

[MelonLoader_24-08-06_03-53-11.860.log](https://github.com/user-attachments/files/16509203/MelonLoader_24-08-06_03-53-11.860.log)

**Comment by capybarajtmc** [comment]
Are you TRYING to stay on patch 3. 3.0.0 is for patch 5 if you don't want to be on patch 3 switch off of the public beta

**Comment by NM69421** [comment]
> Are you TRYING to stay on patch 3. 3.0.0 is for patch 5 if you don't want to be on patch 3 switch off of the public beta

Yes I am. I didn't know Bonelib was Updated to Patch 5, I thought that most code mods were broken by patches 4 and 5. Thank you, I'll just use a older version of bonelib
